USE [BIZPLUS_DB_B2B]
GO

ALTER TABLE [dbo].[BC_MST_SHAIN_XHX] DROP CONSTRAINT [DF_BC_MST_SHAIN_XHX_DEL_FLG]
GO

ALTER TABLE [dbo].[BC_MST_SHAIN_XHX] DROP CONSTRAINT [DF_BC_MST_SHAIN_XHX_MUKOU_FLG]
GO

/****** Object:  Table [dbo].[BC_MST_SHAIN_XHX]    Script Date: 2017/11/28 16:37:41 ******/
DROP TABLE [dbo].[BC_MST_SHAIN_XHX]
GO

/****** Object:  Table [dbo].[BC_MST_SHAIN_XHX]    Script Date: 2017/11/28 16:37:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BC_MST_SHAIN_XHX](
	[KAISHA_CD] [nvarchar](15) NOT NULL,
	[SHAIN_CD] [nvarchar](30) NOT NULL,
	[SHAIN_NM] [nvarchar](40) NULL,
	[SHAIN_KANA] [nvarchar](40) NULL,
	[SHOKUI_KBN] [nvarchar](2) NULL,
	[MAIL] [nvarchar](100) NULL,
	[SHIYOU_STR_TM] [datetime] NULL,
	[SHIYOU_END_TM] [datetime] NULL,
	[USR_UID] [bigint] NULL,
	[MUKOU_FLG] [tinyint] NULL,
	[DEL_FLG] [tinyint] NULL,
	[INS_TM] [datetime] NULL,
	[INS_SHAIN_CD] [nvarchar](30) NULL,
	[INS_PGM_CD] [nvarchar](30) NULL,
	[UPD_TM] [datetime] NULL,
	[UPD_SHAIN_CD] [nvarchar](30) NULL,
	[UPD_PGM_CD] [nvarchar](30) NULL,
 CONSTRAINT [BC_MST_SHAIN_XHX_PK] PRIMARY KEY CLUSTERED 
(
	[KAISHA_CD] ASC,
	[SHAIN_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[BC_MST_SHAIN_XHX] ADD  CONSTRAINT [DF_BC_MST_SHAIN_XHX_MUKOU_FLG]  DEFAULT ((0)) FOR [MUKOU_FLG]
GO

ALTER TABLE [dbo].[BC_MST_SHAIN_XHX] ADD  CONSTRAINT [DF_BC_MST_SHAIN_XHX_DEL_FLG]  DEFAULT ((0)) FOR [DEL_FLG]
GO


